# Generated by Django 4.2 on 2024-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Column name')),
                ('type', models.CharField(choices=[('int', 'Integer'), ('full_name', 'Full name'), ('email', 'Email'), ('job', 'Job'), ('domain_name', 'domain_name'), ('phone_number', 'Phone number'), ('company_name', 'Company name'), ('text', 'Text'), ('address', 'Address'), ('date', 'Date')], max_length=15, verbose_name='Column type')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='Params')),
            ],
            options={
                'verbose_name': 'Column',
                'verbose_name_plural': 'Columns',
            },
        ),
    ]
